#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

/*======================| MQ135 |======================*/

#define MQ135_ADC_PIN GPIO_PIN_0
#define MQ135_ADC_PORT GPIOA
#define MQ135_ADC_CHANNEL ADC_CHANNEL_0

/*======================| GPIO |======================*/
#define BUILTIN_LED_PORT GPIOC
#define BUILTIN_LED_PIN GPIO_PIN_13

#define GPIOA_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()
#define GPIOB_CLK_ENABLE() __HAL_RCC_GPIOB_CLK_ENABLE()
#define GPIOC_CLK_ENABLE() __HAL_RCC_GPIOC_CLK_ENABLE()
#define GPIOD_CLK_ENABLE() __HAL_RCC_GPIOD_CLK_ENABLE()

#define GPIOA_CLK_DISABLE() __HAL_RCC_GPIOA_CLK_DISABLE()
#define GPIOB_CLK_DISABLE() __HAL_RCC_GPIOB_CLK_DISABLE()
#define GPIOC_CLK_DISABLE() __HAL_RCC_GPIOC_CLK_DISABLE()
#define GPIOD_CLK_DISABLE() __HAL_RCC_GPIOD_CLK_DISABLE()

/*======================| UART |======================*/

#define USART1_INSTANCE USART1
#define USART1_BUADRATE 115200

#define USART1_TX_PORT GPIOA
#define USART1_TX_PIN GPIO_PIN_9
#define USART1_RX_PORT GPIOA
#define USART1_RX_PIN GPIO_PIN_10

#define USART1_IRQn USART1_IRQn

#define USART1_CLK_ENABLE() __HAL_RCC_USART1_CLK_ENABLE()
#define USART1_CLK_DISABLE() __HAL_RCC_USART1_CLK_DISABLE()
#define USART1_GPIO_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()
#define USART1_GPIO_CLK_DISABLE() __HAL_RCC_GPIOA_CLK_DISABLE()

/*======================| ADC |======================*/

#define ADC1_INSTANCE ADC1
#define ADC1_SCAN_CONV_MODE ADC_SCAN_DISABLE
#define ADC1_CONT_CONV_MODE ENABLE
#define ADC1_DISCONT_CONV_MODE DISABLE
#define ADC1_EXT_TRIG_CONV ADC_SOFTWARE_START

#define ADC1_SAMPLING_TIME ADC_SAMPLETIME_1CYCLE_5

#define ADC1_CLK_ENABLE() __HAL_RCC_ADC1_CLK_ENABLE()
#define ADC1_CLK_DISABLE() __HAL_RCC_ADC1_CLK_DISABLE()

#endif // BOARD_CONFIG_H